### ISSUE TITLE
Feature unmount, update and refs

### ISSUE THREAD

**Issue by nikku** [bpmn-io/svelte-bpmn#1]
As part of the [Diagram component](https://github.com/pinussilvestrus/bpmn-js-svelte-example/blob/master/src/components/Diagram.svelte) you may feature a bunch of additional Svelte core features and their interaction with bpmn-js:

* unMount
* update
* refs
* reactivity

So a more complete example could look something like this:

```html
<script>
  import { onMount, onDestroy } from 'svelte';

  import BpmnModeler from 'bpmn-js/lib/Modeler';

  const noop = () => {};

  export let xml = '';
  export let onLoaded = noop;
  export let onError = noop;

  let canvas;
  let modeler;

  onMount(() => {

    modeler = new BpmnModeler({
      container: canvas,
      keyboard: { bindTo: canvas }
    });;

    modeler.on('import.done', event => {

      const { error } = event;

      if (error) {
        return onError(error);
      }

      const canvas = modeler.get('canvas');
      canvas.zoom('fit-viewport');

      return onLoaded(event);
    });
  });

  onDestroy(() => {
    modeler.destroy();
  });

  // svelte reactivity: Re-import diagram whenever xml changes
  $: modeler.importXML(xml);
</script>

<style>
  .canvas {
    height: 100%;
    padding: 0;
    margin: 0;
  }
</style>

<div class="canvas" bind:this={canvas}>
</div>
```

**Comment by H0mAUnm** [comment]
replace this line: 
$: modeler.importXML(xml);

with these:
  $: (xml) => {
    if (modeler) {
      modeler.importXML(xml);
    }
  };

**Comment by nikku** [comment]
Does the first line not work?

**Comment by Homayoun-MH** [comment]
> Does the first line not work?

Hi, no it doesn't.
Simply because "Svelte's reactivity is triggered by assignments".
https://svelte.dev/tutorial/updating-arrays-and-objects

**Comment by pinussilvestrus** [comment]
> $: modeler.importXML(xml);

I think @Homayoun-MH means this won't work because the `modeler` only gets initialized on mount. The expression will be evaluated the first time before the first mount happens.

**Comment by pinussilvestrus** [comment]
I will clean this one up in my current slack time. 👍
