### ISSUE TITLE
Consider move this example to a usable Svelte component

### ISSUE THREAD

**Issue by pinussilvestrus** [bpmn-io/svelte-bpmn#2]
__What should we do?__

We could make this example as a usable Svelte component as we have it e.g. in the [react project](https://github.com/bpmn-io/react-bpmn)

__Why should we do it?__

Imagine building on top of changes described in #1 this could offer our users a good and ready-to-use component for there svelte applications.

**Comment by nikku** [comment]
How close are we to actually doing this? Would be amazing if svelte users had something, out of the box.

**Comment by nikku** [comment]
Also, `svelte-bpmn` is [still available for grabbing](https://www.npmjs.com/search?q=svelte-bpmn).

**Comment by pinussilvestrus** [comment]
Pretty close I guess: https://github.com/bpmn-io/bpmn-js-example-svelte/pull/3
